print ("hello world")
print ("hello once again!")
print ("i like typing this")
print ("This is fun!")
print ("Yay! Printing.")
print ("I'd much rather you 'not'.")
print ('I "said" do not touch this.')
print (2**1000)